# Generated by Django 5.2 on 2025-04-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budget_user_expense_user_income_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
