# Generated by Django 5.2 on 2025-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_budget_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=4),
        ),
    ]
