# Generated by Django 5.2 on 2025-04-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(),
        ),
    ]
